config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        get   "tasks",          to: "tasks#index"
        # o route de new tem que vir antes do show para criar o id
        get   "tasks/new",      to: "tasks#new"
        # o as: tem que se chamar task no singular por convenção
        get   "tasks/:id",      to: "tasks#show",    as: "task"
        post  "tasks",          to: "tasks#create",  as: "create"
        get   "tasks/:id/edit", to: "tasks#edit",    as: "edit"
        patch "tasks/:id",      to: "tasks#update",  as: "update"
        delete "tasks/:id",     to: "tasks#destroy", as: "destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  # Mostra a descrição de uma task de tasks
  def show
    @task = Task.find(params[:id])
  end
  # pega as informações para criar uma task com create
  def new
    @task = Task.new
  end
  # cria uma nova task
  def create
    # @task = Task.new(params[:task])
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end
  # edita uma task exixtente
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    # @task.update(params[:task])
    @task.update(task_params)
    redirect_to tasks_path
  end
  # deleta uma task acionando um link
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2> Tarefa a editar: </h2>

<%= render 'form' %>

<p><%= link_to "Voltar para todas as tarefas", tasks_path %></p>

app/views/tasks/index.html.erb
<h2>List all tasks</h2>
<% @tasks.each do |task| %>
  <p> Nome da tarefa: <%= task.name %></p>
  <p> Descrição da tarefa: <%= task.description %>
  <%= link_to "Descrição", task_path(task) %>
  <%= link_to "Delete", task_path(task), method: :delete %>
  <%= link_to "Edit", edit_path(task) %></p>
<% end %>

<%= link_to "Create new", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h2> from new.html.erb </h2>

<%= render 'form' %>

<p><%= link_to "Voltar para todas as tarefas", tasks_path %></p>

app/views/tasks/show.html.erb
<p><%= @task.name %> <%= @task.description %></p>
<p><%= link_to "Voltar para todas as tarefas", tasks_path %></p>